name: env_data_b
channels:
  - conda-forge
dependencies:
  - python=3.9  # Specify the Python version if needed
  - requests    # For HTTP requests
  - xarray      # For handling multidimensional datasets
  - scipy